### ISSUE TITLE
Downloading package not working using apache

### ISSUE THREAD

**Issue by mikkeljohnsen** [JunielKatarn/simple-nuget-server#1]
Did you ever get download of package working with apache ?

https://github.com/Daniel15/simple-nuget-server/issues/20

**Comment by samangh** [comment]
Thank you for your work on the apache fork @JunielKatarn.

Did you ever get the chance to look into this issue?

**Comment by JunielKatarn** [comment]
Hi @samangh. I have not worked in this project for a while.
I did learn about a pretty robust PHP-based REST API, called [Apigility](https://apigility.org/).
It may be worth to fully re-implement the NuGet API in that framework, for it eliminates most of the manual wiring with the HTTP protocol.
Again, no current plans for working on it.

**Comment by mikkeljohnsen** [comment]
Will transition to Github Nuget server when available.
